version: 2
updates:
  - package-ecosystem: "npm"  # Replace with your package manager
    directory: "/"  # Replace with the directory to monitor
    schedule:
      interval: "daily"  # Update frequency (daily, weekly, or monthly)
