---
name: Documentation Issue
about: Report an issue with the project documentation
title: "[Documentation] "

---

body:
  - type: markdown
    attributes:
      value: |
        <!--
        Please follow the guidelines below to report documentation issues effectively.
        -->
        ### Issue Summary
        **Description:**
        A clear and concise description of the problem with the documentation or the improvement you'd like to suggest.

        **Severity:**
        [ ] Low
        [ ] Medium
        [ ] High
        [ ] Critical

        **Affected Documentation Section:**
        Specify the relevant section(s) or page(s) of the documentation where you encountered the issue.

        ### Expected Documentation
        **Describe the expected content:**
        If applicable, describe how you expected the documentation to be or provide examples of how it could be improved.

        **Proposed Solution:**
        Share your ideas for improving the documentation or propose a solution if you have one.

        ### Reproduction Steps
        **Steps to Reproduce:**
        If the issue is related to inaccuracies or unclear instructions, provide the steps to reproduce the problem.

        **Screenshots or Code Snippets:**
        Attach any relevant screenshots or code snippets that illustrate the problem.

        ### Environment Information
        **Your Environment:**
        - OS: [e.g., Windows, macOS, Linux]
        - Browser: [e.g., Chrome, Firefox, Safari]
        - Version: [e.g., 1.0.0]

        **Additional Context:**
        Add any other context or details that might be helpful for understanding the issue.

        ### Related Documentation URLs
        **Links:**
        If relevant, provide any specific URLs or links to the documentation in question.

        ### Contributor Checklist
        Please make sure that you have considered the following before submitting this documentation issue:
        - [ ] I have checked the project's existing documentation issues to ensure there are no duplicates.
        - [ ] I have reviewed the project's CONTRIBUTING guidelines.
        - [ ] I understand that submitting a documentation issue does not guarantee immediate updates.

        ### Additional Notes
        **Notes:**
        Add any other notes or comments related to this documentation issue.
        <!-- 
        Thank you for contributing to our project's documentation! 
        Please make sure to review our CONTRIBUTING guidelines before submitting your issue.
        -->