name: Greeting
on:
  pull_request:
    types: [opened]
  issues:
    types: [opened]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/welcome@v1
        with:
          FIRST_ISSUE: |
            👋 @{{ author }}
            Thanks for opening a issue, your contribution is valuable to us. The maintainers will review this issue and provide feedback as soon as possible!

          FIRST_PR: |
            👋 @{{ author }}
            Thanks for rising a Pull request, your contribution is valuable to us. The maintainers will review this Pull Request and provide feedback as soon as possible. Keep the great work up!

          FIRST_PR_MERGED: |
            🎉 @{{ author }}
            Congrats on merging your first pull request! We appreciate your contribution in AR-Webstore!